import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ThemeProvider from '../components/ThemeProvider';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { QueryProvider } from '@/query/QueryProvider';
import ContextProvider from '@/context/ContextProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
          <ContextProvider>
            <ThemeProvider>
              <Header />
              <main className="min-h-[60vh] pt-20">{children}</main>
              <Footer />
            </ThemeProvider>
          </ContextProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
